name: 'taxi_dbt'
version: '1.0.0'

profile: 'taxi_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"
models:
  taxi_dbt:
    example:
      +materialized: view

seeds:
  taxi_dbt:
    yellow_tripdata_2023-01-cleaned:
      path: data/yellow_tripdata_2023-01-cleaned.csv

