version: 2

models:
  - name: trip_summary
    description: "Daily summary of NYC taxi trips with trip count, average fare, and distance."
    columns:
      - name: trip_date
        description: "The pickup date"
        tests:
          - not_null
          - unique
      - name: trip_count
        description: "Number of trips that day"
        tests:
          - not_null
      - name: avg_fare
        description: "Average fare for that day"
      - name: avg_distance
        description: "Average trip distance for that day"

  - name: hourly_summary
    description: "Hourly summary showing trip counts and average fare per pickup hour."
    columns:
      - name: pickup_hour
        description: "Hour of the day when pickup occurred"
        tests:
          - not_null
      - name: trip_count
        description: "Number of trips in that hour"
        tests:
          - not_null
      - name: avg_fare
        description: "Average fare in that hour"

  - name: fare_buckets
    description: "Breakdown of trips into fare ranges with average distance."
    columns:
      - name: fare_range
        description: "Fare category (e.g. Under $10)"
        tests:
          - not_null
      - name: trip_count
        description: "Number of trips in this fare range"
        tests:
          - not_null
      - name: avg_distance
        description: "Average trip distance in this fare range"